import Icon from './Icon';

export const Book = props => <Icon {...props} name="book" />;
export const Chart = props => <Icon {...props} name="chart" />;
export const ClipboardText = props => <Icon {...props} name="clipboard-text" />;
export const CloseCircle = props => <Icon {...props} name="close-circle" />;
export const Danger = props => <Icon {...props} name="danger" />;
export const Dashboard = props => <Icon {...props} name="dashboard" />;
export const GalleryAdd = props => <Icon {...props} name="gallery-add" />;
export const Logout = props => <Icon {...props} name="logout" />;
export const Note2 = props => <Icon {...props} name="note-2" />;
export const Notification = props => <Icon {...props} name="notification" />;
export const Play = props => <Icon {...props} name="play" />;
export const Report = props => <Icon {...props} name="report" />;
export const Search = props => <Icon {...props} name="search" />;
export const Student = props => <Icon {...props} name="student" />;
export const Teacher = props => <Icon {...props} name="teacher" />;
export const TickCircle = props => <Icon {...props} name="tick-circle" />;
export const Timer = props => <Icon {...props} name="timer" />;
export const Trash = props => <Icon {...props} name="trash" />;